Offline deployment - DCOS package and images (#8)
* Support for CentOS 7.2.

* Allow DCOS offline install.

* Load Docker images from a local directory if present.

* Minor cleanup.

* Fallback to eth0 if interface is not found and added script to pull and save Docker images locally from the apps directory.

diff --git a/ansible/roles/pull-binaries/templates/pull-binaries.sh.j2 b/ansible/roles/pull-binaries/templates/pull-binaries.sh.j2
--- a/ansible/roles/pull-binaries/templates/pull-binaries.sh.j2
+++ b/ansible/roles/pull-binaries/templates/pull-binaries.sh.j2
@@ -7,15 +7,20 @@ do
     # Pull docker images
     image=$(jq --raw-output < ${app} 'select(.container.docker.image != null) .container.docker.image')
     if [[ -n ${image} ]] ; then
-        echo "Pulling image ${image}"
-        docker pull ${image}
-        if [[ $? != 0 ]] ; then
-            echo "Docker pull failed. Exiting build."
-            exit 1
+        image_filename=$(echo $image | cut -d\/ -f2).tar.gz
+        if [ -f "{{ ansible_env.PWD }}/images/$image_filename" ]; then
+            echo "Pulling local image ${image} from filesystem"
+            docker load < "{{ ansible_env.PWD }}/images/$image_filename"
+        else
+            echo "Putlling remote image ${image} from Docker Hub"
+            docker pull ${image}
+            if [[ $? != 0 ]] ; then
+                echo "Docker pull failed. Exiting build."
+                exit 1
+            fi
         fi
     fi
 done
-
 
 ### NOTE: This section is likely deprecated. Evaluate and remove later if so. ###
 asset_dir=/opt/netsil/latest/assets
